import { redirect } from 'next/navigation'
import { type NextRequest } from 'next/server'
import { createClient } from '@/lib/supabase/server'

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url)
  
  // 1. Look for the 'code' parameter generated by {{ .ConfirmationURL }}
  const code = searchParams.get('token')
  
  // 2. If you want to redirect them somewhere specific after, grab 'next' (defaults to /shop)
  const next = searchParams.get('next') ?? '/'

  if (code) {
    const supabase = await createClient()

    // 3. The PKCE Handshake: Exchange the code for secure cookies
    const { error } = await supabase.auth.exchangeCodeForSession(code)
    
    if (!error) {
      // Success! Redirect the user to the shop or their intended destination
      redirect(next)
    }
    
    // Log the error in your terminal so you can debug if it fails!
    console.error("Verification failed:", error.message)
  }

  // If there is no code, or the code was expired, send them to your error page
  redirect('/auth/auth-code-error')
}